<a href="https://colab.research.google.com/github/Aradhyagodambe/Python-Colab-Files/blob/main/ML_Fundamnetals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine learning Basics

* Confusion Matrix
* Encoding Techniques
  1.  Label Encoding
  2.  One Hot Encoding
  3. Ordinal Encoding
* Feature Scaling
  * standard Scaler
  * Normalization
    1. MinMax Scalar
    2. MaxAbs Scalar

# Confusion Matrix

1. Type-I Error [Falsse Positive]
2. Type-II Error [False Negative]

Accuracy = [ (True Positive + True Negative)/ (Total Prediction) ]

# Encoding Techniques

In [1]:
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uditjain13/social-media-screen-time-and-mental-health-2026")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/uditjain13/social-media-screen-time-and-mental-health-2026/1.archive...

100%|██████████| 174k/174k [00:00<00:00, 679kB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/uditjain13/social-media-screen-time-and-mental-health-2026/versions/1

In [4]:
SM = pd.read_csv(f"{path}/social_media_screentime_mental_health_2026.csv")

In [6]:
SM.head()

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300000,33,Male,Student,Latin America,TikTok,8,3.2,172,Never,...,9,6,4,6,8,4,No,No,No,At-risk
1,P300001,23,Female,Full-time employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, failed",Yes,At-risk
2,P300002,56,Female,Full-time employed,Africa,Instagram,1,5.3,74,Every night,...,8,7,3,2,3,5,No,No,No,Moderate
3,P300003,13,Male,Student,Europe,YouTube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, failed",Yes,Moderate
4,P300004,36,Female,Student,Asia,LinkedIn,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, succeeded",No,Moderate

# Label Encoding
* Assigns a unique integer to each category.

In [8]:
from sklearn.preprocessing import LabelEncoder

obj = LabelEncoder()

In [15]:
SM[['Encode','most_used_platform']]

      Encode most_used_platform
0          5             TikTok
1          1          Instagram
2          1          Instagram
3          7            YouTube
4          2           LinkedIn
...      ...                ...
6995       4           Snapchat
6996       0           Facebook
6997       2           LinkedIn
6998       4           Snapchat
6999       0           Facebook

[7000 rows x 2 columns]

In [32]:
SM['Encode'] = obj.fit_transform(SM['most_used_platform'])
print(SM['Encode'])

0       5
1       1
2       1
3       7
4       2
       ..
6995    4
6996    0
6997    2
6998    4
6999    0
Name: Encode, Length: 7000, dtype: int64

# One Hot Encoding
* Creates a separate binary column for each category.

In [20]:
En = pd.get_dummies(SM['most_used_platform'],dtype = int)
En

,Facebook,Instagram,LinkedIn,Reddit,Snapchat,TikTok,X/Twitter,YouTube
0,0,0,0,0,0,1,0,0
1,0,1,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1
4,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...
6995,0,0,0,0,1,0,0,0
6996,1,0,0,0,0,0,0,0
6997,0,0,1,0,0,0,0,0
6998,0,0,0,0,1,0,0,0
6999,1,0,0,0,0,0,0,0

# Ordinal Encoding
* Used when categories have a natural order.

In [25]:
from sklearn.preprocessing import OrdinalEncoder

O = OrdinalEncoder()

In [27]:
SM['New'] = O.fit_transform(SM[['occupation']])
SM[['New','occupation']]

      New          occupation
0     4.0             Student
1     0.0  Full-time employed
2     0.0  Full-time employed
3     4.0             Student
4     4.0             Student
...   ...                 ...
6995  1.0  Part-time employed
6996  3.0       Self-employed
6997  5.0          Unemployed
6998  4.0             Student
6999  4.0             Student

[7000 rows x 2 columns]